config/routes.rb
Rails.application.routes.draw do
  # new knights game
  get 'knights', to: 'knights#home'

  get 'knights/game', to: 'knights#game'

end

app/models/application_record.rb
# models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/base_card.rb
# models/base_card.rb
class Base_Card
  attr_reader :name, :description

  def initialize(name, description)
    @name = name
    @description = description
  end
end

app/models/base_lane.rb
# models/BaseLane.rb
class BaseLane
  attr_reader :base, :heros

  def initialize
    @base = nil
    @heros = []
  end

  def add_base(new_base)
    raise 'Expecting a Base_Card.' unless new_base.is_a?(Base_Card)
    @base = new_base
  end

  def remove_base
    card = @base
    @base = nil
    @heros = []
    card
  end

  def add_hero(new_hero, location)
    raise 'Expecting a HeroCard.' unless new_hero.is_a?(Hero_Card)
    @heros[location] = new_hero
  end

  def remove_hero(location)
    removed_card = @heros[location]
    @heros[location] = nil
    removed_card
  end
end

app/models/deck.rb
class Deck
  # attr_reader :deck

  def deal(deck_name)
    case deck_name
    when "bases_deck"
      deck = bases_deck
    when "heros_deck"
      deck = heros_deck
    when "bosses_deck"
      deck = bosses_deck
    else
      return "Error: Deck not found."
    end
    deck
  end

  private

  def shuffle_many(some_array)
    3.times { some_array.shuffle! }
    some_array
  end

  def bases_deck
    deck = []
    for i in 1..10
      card = Base_Card.new("Base #{i}", "")
      deck.push(card)
    end
    shuffle_many(deck)
    deck
  end

  def heros_deck
    deck = []
    for i in 1..20
      card = Hero_Card.new("Hero #{i}", "", 1, 1)
      deck.push(card)
    end
    shuffle_many(deck)
    deck
  end

  def bosses_deck
    deck = []
    for i in 1..10
      card = Hero_Card.new("Boss #{i}", "", 1, 1)
      deck.push(card)
    end
    shuffle_many(deck)

    big_bosses = []
    for i in 1..3
      card = Hero_Card.new("Big Boss #{i}", "", 1, 1)
      big_bosses.push(card)
    end
    shuffle_many(big_bosses)
    deck.push(*big_bosses)
    deck
  end

end

app/models/game.rb
class Game
  attr_reader :current_boss, :user1_hand
  # debug
  attr_reader :bosses_deck, :bases_deck, :heros_deck

  def initialize
    deck = Deck.new

    @bases_deck = []
    @bases_deck.push(*deck.deal("bases_deck"))

    @heros_deck = []
    @heros_deck.push(*deck.deal("heros_deck"))
    @user1_hand = Player_Hand.new

    @bosses_deck = []
    @bosses_deck.push(*deck.deal("bosses_deck"))
    @current_boss = @bosses_deck.shift
  end

  def draw_base_card
    return @bases_pool.draw
  end

end

app/models/hand.rb
class Hand
  attr_reader :base_lanes, :drawn_cards, :discard_pile

  def initialize
    @base_lanes = []
    3.times { @base_lanes.push(Base_Lane.new) }
    @drawn_cards = []
    @discard_pile = []
  end

end

app/models/hero_card.rb
class Hero_Card
  attr_reader :name, :description, :attack, :defense

  def initialize(name, description, attack, defense)
    @name = name
    @description = description
    @attack = attack
    @defense = defense
  end
end

app/models/player_hand.rb
class Player_Hand
  attr_reader :BaseLanes, :drawn_cards, :discard_pile

  def initialize
    @BaseLanes = []
    3.times { @BaseLanes.push(BaseLane.new) }
    @drawn_cards = []
    @discard_pile = []
  end

  def add_drawn_card(new_card)
    if new_card.is_a?(Base_Card) || new_card.is_a?(Hero_Card)
      drawn_cards.push(new_card)
    else
      raise "Expecting a Base_Card or Hero_Card object."
    end
  end

  def move_drawn_base_to_lane(drawn_card_id, lane_id)
    if @drawn_cards[drawn_card_id].nil?
      raise "No card to draw at location #{drawn_card_id}"
    end

    if @drawn_cards[drawn_card_id].is_a?(Hero_Card)
      raise "Expecting a Base_Card object."
    end

    card = @drawn_cards[drawn_card_id]

    if @BaseLanes[lane_id].base != nil
      card_to_discard = @BaseLanes[lane_id].remove_base
      @discard_pile.push(card_to_discard)
    end

    @BaseLanes[lane_id].add_base(card)
    @drawn_cards[drawn_card_id] = nil
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/knights_controller.rb
class KnightsController < ApplicationController

  def home
  end

  def game
    @game = Game.new
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/knights/game.html.erb
<!-- <%= react_component("Test_This", { name: "Hello", description: "Description" }) %> -->
<%= react_component("GameBoard") %>
<%= link_to 'Exit Game', knights_path %>

<h1>Debug</h1>
<div class="">
  <h4>Heros Deck</h4>
  <% @game.heros_deck.each do |card| %>
    Name: <%= card.name %><br />
  <% end %>

  <h4>Bases Deck</h4>
  <% @game.bases_deck.each do |card| %>
    Name: <%= card.name %><br />
  <% end %>

  <h4>Bosses Deck</h4>
  <% @game.bosses_deck.each do |card| %>
    Name: <%= card.name %><br />
  <% end %>
  <h4>Boss Card <%= @game.current_boss.name  %></h4>
</div>

app/views/knights/home.html.erb
<h1>New Base Knights Game</h1>
<%= link_to 'Start a new Base Knights Game!', knights_game_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BaseKnights</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>